import React, { useState } from 'react';
import { 
  Info, 
  Plus, 
  Trash2, 
  CheckCircle, 
  AlertCircle, 
  XCircle, 
  Award, 
  Leaf, 
  Layers, 
  Calendar,
  Sparkles,
  HelpCircle
} from 'lucide-react';
import { ExploitationData, HistoricalFiche, ManualIftTreatment, Parcelle } from '../types';

interface HveIftDashboardProps {
  isDarkMode: boolean;
  exploitationData: ExploitationData;
  historicalFiches: HistoricalFiche[];
  onUpdateCropType: (type: 'grandes_cultures' | 'viticulture' | 'arboriculture') => void;
  onAddManualIft: (date: string, parcelleId: string, appliedDose: number, productConcentration: number, notes?: string) => void;
  onDeleteManualIft: (id: string) => void;
}

export default function HveIftDashboard({
  isDarkMode,
  exploitationData,
  historicalFiches = [],
  onUpdateCropType,
  onAddManualIft,
  onDeleteManualIft
}: HveIftDashboardProps) {
  
  // Set default values in case of legacy loading
  const cropType = exploitationData.hveCropType || 'viticulture';
  const parcelles = exploitationData.parcelles || [];
  const manualTreatments = exploitationData.manualIftTreatments || [];

  // Form states for manual additions
  const [showAddForm, setShowAddForm] = useState(false);
  const [formDate, setFormDate] = useState(new Date().toISOString().split('T')[0]);
  const [formParcelleId, setFormParcelleId] = useState('');
  const [formAppliedDose, setFormAppliedDose] = useState('1.5'); // default L/ha
  const [formConcentration, setFormConcentration] = useState('360'); // default g/L glyphosate
  const [formNotes, setFormNotes] = useState('');
  const [formError, setFormError] = useState<string | null>(null);

  // Configuration for target HVE values
  const cropConfigs = {
    viticulture: {
      label: 'Viticulture (Vigne)',
      refActiveIngredient: 360, // 360 g/ha (representing 1.0 L/ha of 360 g/L glyphosate)
      targetIft: 0.6, // target IFT benchmark
      desc: 'Réglementation stricte : la vigne limite l\'usage du glyphosate à 450 g de matière active/ha/an en inter-rang non labouré, avec des cibles IFT optimales sous 0.6.'
    },
    grandes_cultures: {
      label: 'Grandes Cultures (Arable)',
      refActiveIngredient: 1080, // 1080 g/ha (representing 3.0 L/ha of 360 g/L glyphosate)
      targetIft: 1.0, // target IFT benchmark
      desc: 'Pour les céréales et protéagineux, la dose de référence standard est de 1080 g/ha/an. La cible IFT herbi sous HVE est de 1.0 pour valider l\'excellence.'
    },
    arboriculture: {
      label: 'Arboriculture / Verger',
      refActiveIngredient: 540, // 540 g/ha (representing 1.5 L/ha of 360 g/L glyphosate)
      targetIft: 0.8, // target IFT benchmark
      desc: 'Les vergers disposent d\'une dose de référence fixée à 540 g/ha/an sous l\'arbre, ciblant un indicateur IFT de 0.8.'
    }
  };

  const currentConfig = cropConfigs[cropType];

  // Helper function to extract and standardise treatments
  const getUnifiedTreatments = () => {
    const list: Array<{
      id: string;
      source: 'fiche' | 'manuel';
      date: string;
      parcelleId: string;
      parcelleNom: string;
      appliedDose: number; // L/ha
      concentration: number; // g/L
      notes?: string;
      computedIft: number;
    }> = [];

    // 1. Core extractor from historical fiches (reports generated by this domain)
    historicalFiches.forEach(fiche => {
      if (fiche.mode !== 'agri') return;
      
      // Attempt to link this fiche to a parcel in the active domain
      // Either by name match or by verifying if it was generated under this domain
      const ficheParcelName = fiche.ficheInputs.parcelle || '';
      const matchedParcel = parcelles.find(p => 
        p.name.toLowerCase().trim() === ficheParcelName.toLowerCase().trim()
      );

      if (matchedParcel) {
        // Fallback parsers for legacy fiches which don't have the explicit numeric values
        let surf = fiche.details.rawSurface;
        if (surf === undefined) {
          const match = fiche.details.surface.match(/[\d.]+/);
          surf = match ? parseFloat(match[0]) : matchedParcel.surface;
        }

        let totalProd = fiche.details.rawTotalProduct;
        if (totalProd === undefined) {
          const match = fiche.details.totalProduct.match(/[\d.]+/);
          totalProd = match ? parseFloat(match[0]) : 0;
        }

        let dose = fiche.details.rawDoseProduct;
        if (dose === undefined || dose === 0) {
          dose = surf > 0 ? totalProd / surf : 0;
        }

        const concentration = fiche.details.productConcentration || 360;

        // Apply formula: IFT = applied Dose * concentration / reference active ingredient
        const computedIft = (dose * concentration) / currentConfig.refActiveIngredient;

        list.push({
          id: fiche.id,
          source: 'fiche',
          date: fiche.ficheInputs.date || fiche.dateGen.split(' à ')[0] || '',
          parcelleId: matchedParcel.id,
          parcelleNom: matchedParcel.name,
          appliedDose: Math.round(dose * 100) / 100,
          concentration,
          notes: `Généré automatiquement via Fiche PDF (${fiche.fileName})`,
          computedIft: Math.round(computedIft * 100) / 100
        });
      }
    });

    // 2. Extra handlers for manual inputs
    manualTreatments.forEach(tr => {
      const matchedParcel = parcelles.find(p => p.id === tr.parcelle);
      const computedIft = (tr.appliedDose * tr.productConcentration) / currentConfig.refActiveIngredient;

      list.push({
        id: tr.id,
        source: 'manuel',
        date: tr.date,
        parcelleId: tr.parcelle,
        parcelleNom: matchedParcel ? matchedParcel.name : 'Parcelle inconnue',
        appliedDose: tr.appliedDose,
        concentration: tr.productConcentration,
        notes: tr.notes || 'Saisie manuelle',
        computedIft: Math.round(computedIft * 100) / 100
      });
    });

    // Sort by date descending
    return list.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  };

  const treatments = getUnifiedTreatments();

  // Parcel-by-parcel calculations
  const parcelIftDetails = parcelles.map(parcel => {
    // Sum of all treatment IFTs executed on this specific parcel
    const parcelTreatments = treatments.filter(t => t.parcelleId === parcel.id);
    const sumIft = parcelTreatments.reduce((acc, t) => acc + t.computedIft, 0);

    return {
      id: parcel.id,
      name: parcel.name,
      surface: parcel.surface,
      treatmentsCount: parcelTreatments.length,
      totalIft: Math.round(sumIft * 100) / 100
    };
  });

  // Calculate exploitation overall weighted average IFT
  const totalSurface = parcelles.reduce((acc, p) => acc + p.surface, 0);
  
  // Weighted IFT sum = Sum(Parcel Total IFT * Parcel Surface)
  const weightedIftSum = parcelIftDetails.reduce((acc, p) => acc + (p.totalIft * p.surface), 0);
  const globalIft = totalSurface > 0 ? Math.round((weightedIftSum / totalSurface) * 100) / 100 : 0;

  // HVE Verification status
  const targetBenchmark = currentConfig.targetIft;
  let complianceStatus: 'excellent' | 'warning' | 'error' = 'excellent';
  if (globalIft > targetBenchmark * 1.5) {
    complianceStatus = 'error';
  } else if (globalIft > targetBenchmark) {
    complianceStatus = 'warning';
  }

  // Handle Form Submission
  const handleSubmitManual = (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    if (!formParcelleId) {
      setFormError('Veuillez sélectionner une parcelle.');
      return;
    }

    const applied = parseFloat(formAppliedDose);
    if (isNaN(applied) || applied <= 0) {
      setFormError('La dose appliquée doit être supérieure à 0.');
      return;
    }

    const conc = parseFloat(formConcentration);
    if (isNaN(conc) || conc <= 0) {
      setFormError('La concentration du produit doit être supérieure à 0.');
      return;
    }

    onAddManualIft(formDate, formParcelleId, applied, conc, formNotes.trim() || undefined);
    
    // Reset form
    setFormNotes('');
    setShowAddForm(false);
  };

  return (
    <div id="hve-ift-dashboard" className={`p-6 rounded-2xl border ${
      isDarkMode ? 'bg-slate-900 border-slate-800' : 'bg-white border-slate-200/90 shadow-sm'
    }`}>
      {/* Header Title with Sprout Theme */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 pb-5 border-b border-slate-200/60 dark:border-slate-800">
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-xl bg-emerald-500/15 text-emerald-600 dark:text-emerald-400">
            <Leaf className="w-6 h-6 animate-pulse" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white">Calculateur d'IFT & Diagnostic HVE</h2>
              <span className="text-[10px] bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 font-bold px-2.5 py-0.5 rounded-full border border-emerald-500/20 shadow-xs">
                Normes 2026 actives
              </span>
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Calcul et traçabilité réglementaire de l'Indicateur de Fréquence de Traitement pour l'autorisation environnementale.
            </p>
          </div>
        </div>

        {/* Culture Switcher */}
        <div className="flex items-center gap-2">
          <label className="text-xs font-semibold text-slate-500 dark:text-slate-400">
            Type de culture :
          </label>
          <select
            value={cropType}
            onChange={(e) => onUpdateCropType(e.target.value as any)}
            className={`text-xs font-bold pl-3 pr-8 py-2 rounded-xl border focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 transition-all cursor-pointer outline-hidden ${
              isDarkMode ? 'bg-slate-950 border-slate-800 text-slate-200' : 'bg-slate-50 border-slate-200 text-slate-800'
            }`}
          >
            <option value="viticulture">🍇 Viticulture (Vignes)</option>
            <option value="grandes_cultures">🌾 Grandes Cultures (Arable)</option>
            <option value="arboriculture">🍎 Arboriculture (Vergers)</option>
          </select>
        </div>
      </div>

      {/* Main KPI Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 mb-6">
        
        {/* left column: circular visual gauge & summary */}
        <div className={`lg:col-span-4 p-5 rounded-xl border flex flex-col items-center justify-center text-center ${
          isDarkMode ? 'bg-slate-950/40 border-slate-800' : 'bg-slate-550/5 bg-slate-50/80 border-slate-100'
        }`}>
          <span className="text-[10px] font-bold text-slate-400 dark:text-slate-500 tracking-wider uppercase mb-3">
            IFT Herbicide Global
          </span>

          {/* Visual Circle Gauge */}
          <div className="relative flex items-center justify-center w-36 h-36 mb-4">
            {/* SVG circle meter */}
            <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
              <circle
                cx="50"
                cy="50"
                r="40"
                fill="transparent"
                stroke={isDarkMode ? '#1e293b' : '#f1f5f9'}
                strokeWidth="8"
              />
              <circle
                cx="50"
                cy="50"
                r="40"
                fill="transparent"
                stroke={
                  complianceStatus === 'excellent' ? '#10b981' : 
                  complianceStatus === 'warning' ? '#f59e0b' : '#ef4444'
                }
                strokeWidth="8"
                strokeDasharray={`${Math.min((globalIft / (targetBenchmark * 2)) * 251.2, 251.2)} 251.2`}
                strokeLinecap="round"
                className="transition-all duration-500"
              />
            </svg>
            <div className="absolute flex flex-col items-center justify-center">
              <span className={`text-3xl font-black ${
                complianceStatus === 'excellent' ? 'text-emerald-500' :
                complianceStatus === 'warning' ? 'text-amber-500' : 'text-red-500'
              }`}>
                {globalIft.toFixed(2)}
              </span>
              <span className="text-[9px] text-slate-400 dark:text-slate-500 font-semibold mt-0.5">
                Cible HVE ≤ {targetBenchmark.toFixed(1)}
              </span>
            </div>
          </div>

          {/* Compliance Status Notification Badge */}
          {complianceStatus === 'excellent' && (
            <div className="flex items-center gap-1.5 px-3 py-1 bg-emerald-500/10 border border-emerald-500/25 text-emerald-600 dark:text-emerald-400 rounded-full font-bold text-xs">
              <CheckCircle className="w-3.5 h-3.5" />
              <span>Diagnostic Excellent (HVE +5 Pts)</span>
            </div>
          )}
          {complianceStatus === 'warning' && (
            <div className="flex items-center gap-1.5 px-3 py-1 bg-amber-500/10 border border-amber-500/25 text-amber-600 dark:text-amber-400 rounded-full font-bold text-xs">
              <AlertCircle className="w-3.5 h-3.5" />
              <span>Seuil HVE Approché / Dépassé</span>
            </div>
          )}
          {complianceStatus === 'error' && (
            <div className="flex items-center gap-1.5 px-3 py-1 bg-red-500/10 border border-red-500/25 text-red-600 dark:text-red-400 rounded-full font-bold text-xs">
              <XCircle className="w-3.5 h-3.5" />
              <span>Dépassement Critique HVE</span>
            </div>
          )}

          <p className="text-[10px] text-slate-400 dark:text-slate-500 mt-4 leading-relaxed">
            Moyenne pondérée calculée sur <strong>{totalSurface.toFixed(1)} ha</strong> d'exploitation répartis sur <strong>{parcelles.length}</strong> parcelles.
          </p>
        </div>

        {/* Right column: benchmark details & educational summary */}
        <div className="lg:col-span-8 flex flex-col justify-between gap-4">
          <div className={`p-4 rounded-xl border h-full flex flex-col justify-between ${
            isDarkMode ? 'bg-slate-950/20 border-slate-800' : 'bg-white border-slate-200'
          }`}>
            <div>
              <div className="flex items-center gap-2 mb-2 text-slate-900 dark:text-slate-100">
                <Award className="w-4 h-4 text-amber-500" />
                <h3 className="font-bold text-xs text-slate-800 dark:text-slate-200 uppercase tracking-wide">
                  Réglementation HVE de l'indicateur IFT Herbicides
                </h3>
              </div>
              <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                {currentConfig.desc}
              </p>
            </div>

            {/* List of configuration variables in simple grid */}
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3 my-4">
              <div className={`p-3 rounded-lg border flex flex-col ${isDarkMode ? 'bg-slate-950 border-slate-800/80' : 'bg-slate-50 border-slate-100'}`}>
                <span className="text-[10px] text-slate-400 dark:text-slate-500">Matière Active de Réf.</span>
                <span className="text-xs font-bold text-slate-800 dark:text-slate-200 md:text-sm mt-0.5">
                  {currentConfig.refActiveIngredient} g/ha
                </span>
              </div>
              <div className={`p-3 rounded-lg border flex flex-col ${isDarkMode ? 'bg-slate-950 border-slate-800/80' : 'bg-slate-50 border-slate-100'}`}>
                <span className="text-[10px] text-slate-400 dark:text-slate-500">Vol. de Réf. (360 g/L)</span>
                <span className="text-xs font-bold text-slate-800 dark:text-slate-200 md:text-sm mt-0.5">
                  {(currentConfig.refActiveIngredient / 360).toFixed(2)} L/ha
                </span>
              </div>
              <div className={`p-3 rounded-lg border flex flex-col col-span-2 md:col-span-1 ${isDarkMode ? 'bg-slate-950 border-slate-800/80' : 'bg-slate-50 border-slate-100'}`}>
                <span className="text-[10px] text-slate-400 dark:text-slate-500">Seuil Excellence HVE</span>
                <span className="text-xs font-bold text-emerald-500 md:text-sm mt-0.5">
                  ≤ {targetBenchmark.toFixed(1)}
                </span>
              </div>
            </div>

            {/* Micro warning note */}
            <div className="flex items-start gap-2 text-[11px] text-slate-400 dark:text-slate-500 bg-amber-500/5 dark:bg-amber-500/2 p-3 rounded-lg border border-amber-500/10">
              <Info className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
              <span>
                <strong>Comment baisser l'IFT ?</strong> Augmentez la proportion d'enherbement sur l'exploitation, favorisez le binage mécanique inter-rang et réduisez la concentration active en incorporant du sulfate d'ammonium ou de l'eau adoucie.
              </span>
            </div>
          </div>
        </div>

      </div>

      {/* Parcel-by-parcel detailing bar */}
      <div className="mb-6">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-3 flex items-center gap-1.5">
          <Layers className="w-4 h-4" />
          Détail de l'Indicateur IFT par Parcelle
        </h3>

        {parcelles.length === 0 ? (
          <div className="p-5 border border-dashed rounded-xl text-center text-xs text-slate-400">
            Aucune parcelle n'est configurée pour cette exploitation. Configurez vos parcelles ci-dessus pour réaliser le diagnostic.
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {parcelIftDetails.map(pi => {
              // compliance percentage compared to benchmark
              const pct = pi.totalIft > 0 ? (pi.totalIft / targetBenchmark) * 100 : 0;
              let barColor = 'bg-emerald-500';
              let textColor = 'text-emerald-500';
              if (pi.totalIft > targetBenchmark * 1.5) {
                barColor = 'bg-red-500';
                textColor = 'text-red-500';
              } else if (pi.totalIft > targetBenchmark) {
                barColor = 'bg-amber-500';
                textColor = 'text-amber-500';
              }

              return (
                <div 
                  key={pi.id} 
                  className={`p-4 rounded-xl border flex flex-col justify-between ${
                    isDarkMode ? 'bg-slate-950/30 border-slate-800' : 'bg-white border-slate-200'
                  }`}
                >
                  <div className="flex items-center justify-between gap-1 mb-2">
                    <span className="font-bold text-xs text-slate-800 dark:text-slate-200 truncate pr-2">
                      {pi.name}
                    </span>
                    <span className="text-[10px] font-mono text-slate-400 uppercase shrink-0">
                      {pi.surface.toFixed(1)} ha
                    </span>
                  </div>

                  <div className="flex items-baseline justify-between mb-2">
                    <span className="text-[10px] text-slate-400 dark:text-slate-500">
                      ({pi.treatmentsCount} traitement{pi.treatmentsCount > 1 ? 's' : ''})
                    </span>
                    <span className={`text-base font-extrabold ${textColor}`}>
                      IFT {pi.totalIft.toFixed(2)}
                    </span>
                  </div>

                  {/* Progress bar */}
                  <div className="w-full h-1.5 bg-slate-200 dark:bg-slate-800 rounded-full overflow-hidden">
                    <div 
                      className={`h-full ${barColor} rounded-full transition-all duration-300`} 
                      style={{ width: `${Math.min(pct, 100)}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Treatments List & Add Panel */}
      <div>
        <div className="flex items-center justify-between pb-3 border-b border-slate-200/80 dark:border-slate-800 mb-4">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 flex items-center gap-1.5">
            <Calendar className="w-4 h-4" />
            Historique des Applications & Traitements Actifs ({treatments.length})
          </h3>
          
          <button
            type="button"
            onClick={() => setShowAddForm(!showAddForm)}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold rounded-lg text-white bg-emerald-600 hover:bg-emerald-700 transition-all cursor-pointer shadow-xs"
          >
            <Plus className="w-3.5 h-3.5" />
            {showAddForm ? 'Annuler' : 'Ajouter un traitement'}
          </button>
        </div>

        {/* 1. Add Form */}
        {showAddForm && (
          <form 
            onSubmit={handleSubmitManual}
            className={`p-4 rounded-xl border mb-4 grid grid-cols-1 md:grid-cols-12 gap-4 ${
              isDarkMode ? 'bg-slate-950/60 border-slate-800' : 'bg-slate-50 border-slate-100 shadow-inner'
            }`}
          >
            {/* Form Title banner */}
            <div className="col-span-1 md:col-span-12 flex items-center gap-1 text-xs font-bold text-slate-800 dark:text-slate-200">
              <Sparkles className="w-4 h-4 text-emerald-500" />
              <span>Simuler ou Enregistrer un traitement hors application</span>
            </div>

            {/* Error messaging */}
            {formError && (
              <div className="col-span-1 md:col-span-12 p-2.5 rounded-lg bg-red-500/10 border border-red-500/25 text-red-500 text-xs font-bold flex items-center gap-2">
                <AlertCircle className="w-4 h-4 shrink-0" />
                <span>{formError}</span>
              </div>
            )}

            {/* Date input */}
            <div className="col-span-1 md:col-span-3">
              <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1">
                Date d'application
              </label>
              <input
                type="date"
                required
                value={formDate}
                onChange={(e) => setFormDate(e.target.value)}
                className={`w-full p-2.5 rounded-lg text-xs font-semibold border focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 transition-all outline-hidden ${
                  isDarkMode ? 'bg-slate-950 border-slate-800 text-slate-100' : 'bg-white border-slate-200 text-slate-800'
                }`}
              />
            </div>

            {/* Parcelle selection */}
            <div className="col-span-1 md:col-span-3">
              <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1">
                Parcelle appliquée
              </label>
              <select
                required
                value={formParcelleId}
                onChange={(e) => setFormParcelleId(e.target.value)}
                className={`w-full p-2.5 rounded-lg text-xs font-semibold border focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 transition-all cursor-pointer outline-hidden ${
                  isDarkMode ? 'bg-slate-950 border-slate-800 text-slate-100' : 'bg-white border-slate-200 text-slate-800'
                }`}
              >
                <option value="">Sélectionner...</option>
                {parcelles.map(p => (
                  <option key={p.id} value={p.id}>
                    {p.name} ({p.surface.toFixed(1)} ha)
                  </option>
                ))}
              </select>
            </div>

            {/* Applied Dose (L/ha) */}
            <div className="col-span-1 md:col-span-2">
              <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1 flex items-center gap-1">
                Dose (L/ha)
                <HelpCircle className="w-3 h-3 text-slate-400" title="Dose de produit commercial appliqué à l'hectare." />
              </label>
              <input
                type="number"
                step="0.01"
                min="0.05"
                required
                value={formAppliedDose}
                onChange={(e) => setFormAppliedDose(e.target.value)}
                className={`w-full p-2.5 rounded-lg text-xs font-bold border focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 transition-all outline-hidden ${
                  isDarkMode ? 'bg-slate-950 border-slate-800 text-slate-100' : 'bg-white border-slate-200 text-slate-800'
                }`}
              />
            </div>

            {/* Formulation strength Concentration g/L */}
            <div className="col-span-1 md:col-span-2">
              <label className="block text-[10px] font-bold text-slate-400 uppercase mb-1 flex items-center gap-1">
                Concentration (g/L)
                <HelpCircle className="w-3 h-3 text-slate-400" title="Généralement 360, 450 ou 480 g/L de glyphosate." />
              </label>
              <select
                value={formConcentration}
                onChange={(e) => setFormConcentration(e.target.value)}
                className={`w-full p-2.5 rounded-lg text-xs font-bold border focus:ring-1 focus:ring-emerald-500 focus:border-emerald-500 transition-all cursor-pointer outline-hidden ${
                  isDarkMode ? 'bg-slate-950 border-slate-800 text-slate-100' : 'bg-white border-slate-200 text-slate-800'
                }`}
              >
                <option value="360">360 g/L (Classique)</option>
                <option value="450">450 g/L (Concentré)</option>
                <option value="480">480 g/L (Maxi)</option>
                <option value="500">500 g/L (Technique)</option>
              </select>
            </div>

            {/* Notes */}
            <div className="col-span-1 md:col-span-2 flex items-end">
              <button
                type="submit"
                className="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs py-3 rounded-lg transition-all shadow-xs cursor-pointer"
              >
                Saisir Treatment
              </button>
            </div>
          </form>
        )}

        {/* 2. Treatments Table */}
        {treatments.length === 0 ? (
          <div className="p-8 text-center text-xs text-slate-400 border border-dashed rounded-xl">
            Aucun traitement enregistré dans l'application pour cette exploitation. Remplissez des fiches de traitement agricole "Calculateur" ou ajoutez un traitement manuellement pour alimenter l'IFT.
          </div>
        ) : (
          <div className="overflow-x-auto rounded-xl border border-slate-200/80 dark:border-slate-800">
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className={isDarkMode ? 'bg-slate-950 text-slate-400' : 'bg-slate-50 text-slate-500'}>
                  <th className="p-3.5 font-bold">Date</th>
                  <th className="p-3.5 font-bold">Parcelle</th>
                  <th className="p-3.5 font-bold">Source</th>
                  <th className="p-3.5 font-bold text-right">Dose appliquée</th>
                  <th className="p-3.5 font-bold text-right" title="Indicateur de concentration active du principe glyphosate.">Glyphosate (g/L)</th>
                  <th className="p-3.5 font-bold text-right">Calcul IFT</th>
                  <th className="p-3.5 font-bold text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800/80">
                {treatments.map((tr) => (
                  <tr 
                    key={tr.id} 
                    className={`hover:bg-slate-50/50 dark:hover:bg-slate-950/20 group transition-all`}
                  >
                    <td className="p-3.5 font-bold text-slate-800 dark:text-slate-200">
                      {new Date(tr.date).toLocaleDateString('fr-FR', { day: '2-digit', month: 'short', year: 'numeric' })}
                    </td>
                    <td className="p-3.5">
                      <div className="font-semibold text-slate-800 dark:text-slate-200">{tr.parcelleNom}</div>
                      <div className="text-[10px] text-slate-400 leading-relaxed max-w-[240px] truncate" title={tr.notes}>
                        {tr.notes}
                      </div>
                    </td>
                    <td className="p-3.5">
                      {tr.source === 'fiche' ? (
                        <span className="inline-flex items-center gap-1 text-[10px] font-bold text-amber-600 dark:text-amber-400 bg-amber-500/10 px-2 py-0.5 rounded-md border border-amber-500/15">
                          Fiche Partagée
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 text-[10px] font-bold text-blue-600 dark:text-blue-400 bg-blue-500/10 px-2 py-0.5 rounded-md border border-blue-500/15">
                          Saisie Manuelle
                        </span>
                      )}
                    </td>
                    <td className="p-3.5 text-right font-bold text-slate-700 dark:text-slate-300">
                      {tr.appliedDose.toFixed(2)} L/ha
                    </td>
                    <td className="p-3.5 text-right font-semibold text-slate-500 dark:text-slate-400">
                      {tr.concentration} g/L
                    </td>
                    <td className="p-3.5 text-right">
                      <span className="font-extrabold text-[13px] text-emerald-500 dark:text-emerald-400">
                        {tr.computedIft.toFixed(2)}
                      </span>
                    </td>
                    <td className="p-3.5 text-right">
                      {tr.source === 'manuel' ? (
                        <button
                          type="button"
                          onClick={() => {
                            if (window.confirm('Voulez-vous supprimer ce traitement de l\'historique IFT ?')) {
                              onDeleteManualIft(tr.id);
                            }
                          }}
                          className="p-1 px-2.5 rounded-lg border border-red-500/10 text-red-500 bg-red-500/5 hover:bg-red-500/10 transition-all text-[11px] font-bold cursor-pointer opacity-75 hover:opacity-100"
                        >
                          <Trash2 className="w-3.5 h-3.5 inline" />
                        </button>
                      ) : (
                        <span className="text-[10px] text-slate-400 font-semibold italic pr-2">Associé PDF</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

    </div>
  );
}
